<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BikeConsulting.Entities\BikeConsulting.Entities.csproj" />
    <ProjectReference Include="..\BikeConsulting.Dto\BikeConsulting.Dto.csproj" />
    <ProjectReference Include="..\BikeConsulting.Framework\BikeConsulting.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.89" />
  </ItemGroup>

</Project>
